name: Publicar Web per SFTP

on:
  push:
    branches:
      - main  # S'executa quan fas push a la branca main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.SFTP_SERVER }}
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        server-dir: /web/  # ⚠️ Ull! Revisa quina és la carpeta del teu servidor
        
        protocol: sftp
        port: 22
        security: loose